version: "3.7"

services:
  ahorcado-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ahorcado-app
    container_name: ahorcado-app-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
